# 各配置的格式字符串
# {platform} 平台(字母形式)
# {roomid}   房间号
# {nick}     主播昵称
# {title}    直播间标题
# {area}     所在分区
# {status}   直播间状态
[format]
# 频道名称
name = '{status}{title}'
# 频道分组
group = '{status};⚙️{area};👤{nick}'
# 频道播放地址
[format.url]
# 默认播放地址
default = 'http://你的IP:端口/{platform}/{roomid}'
# 平台特化播放地址, 如无特殊需求, 一般没有意义
# bilibili = 'https://www.goodiptv.club/{platform}/{roomid}'

# 代理配置
# [proxies]
# http = 'http://127.0.0.1:7890'
# https = 'http://127.0.0.1:7890'

# 使用streamlink解析直播流链接时的option, http-proxy会根据[proxies]自动填充
# [url.option.bilibili]
# http-cookies = 'SESSDATA=xxx; bili_jct=xxx' # 浏览器登录B站后从Cookie中复制, 用于获取1080P+高画质
# [url.option.twitch]
# http-headers = 'Authorization=OAuth鉴权' # 配置鉴权信息可以跳过twitch流中的广告

# 频道不同状态的文案配置
[status]
closed = '❌未开播'
live = '✅直播中'
loop = '🔁轮播'
blocked = '🚫封禁'
exception = '❗异常'
timeout = '⌛超时'

# 各字段正则处理配置, 每条规则为 ["pattern", "replacement"]
[re]
name = [
    [',', '，'],
    ['(?<=^❌)未开播', ''],
    ['(?<=^✅)直播中', ''],
    ['(?<=^🔁)轮播', ''],
    ['(?<=^🚫)封禁', ''],
    ['(?<=^❗)异常', ''],
    ['(?<=^⌛)超时', ''],
]
group = [
    [';;', ';'],
    ['^;|;$', ''],
]
area = [
    [' *\d+$', ''],
]

# 引用已有m3u文件数据
[include.m3u]
# 远程引用
# remote = ['https://raw.githubusercontent.com/CedarHuang/dyn-live-m3u/master/config/example.m3u']
# 本地引用
# local = ['example.m3u']

# 引用其他toml的channel配置
[include.toml]
# 远程引用
# remote = ['https://raw.githubusercontent.com/CedarHuang/dyn-live-m3u/master/config/second.toml']
# 本地引用
# local = ['second.toml']

# 频道简易配置方式, 形如 simple = 'platform:roomid(:hide)', 若配置了hide, 则频道在未开播时自动隐藏
[[channel]]
simple = 'douyu:3484:hide'
[[channel]]
simple = 'bilibili:732'

# 频道详细配置方式, 一般情况下没有意义, 或在想添加暂未支持平台时有所运用
# [[channel]]
# platform = 'youtube'
# roomid = 'qaEdtM10kKg'
# nick = 'Matchroom Multi Sport'
# area = 'sport'
# logo = 'https://yt3.ggpht.com/ytc/AOPolaTnpgKxpulbLGsce6GmJ6hsyTkpCyF9BHPO7yUY=s88-c-k-c0x00ffffff-no-rj'
# status = ''
