[format]
name = '{title}'
group = '{nick}'
[format.url]
default = 'http://Docker宿主机IP:3658/{platform}/{roomid}'

[[channel]]
simple = 'douyu:3484'
[[channel]]
simple = 'huya:15916883'
[[channel]]
simple = 'bilibili:4670738'
