[format]
name = '{title}'
group = '{nick}'
[format.url]
default = 'http://allinone.go.to/{platform}/{roomid}'

[[channel]]
simple = 'douyu:3484'
[[channel]]
simple = 'huya:igxy520'
[[channel]]
simple = 'bilibili:4670738'
